import fs from 'fs';

const t9 = \`# Tema 9. Hoja de Cálculo: Microsoft Excel 365, Lógica y Funciones Matemáticas

## 1. Naturaleza Pura Paramétrica del Libro de Cálculo
Microsoft Excel fundamenta su estructura no en párrafos ni flujos continuos como Word, sino en celdas estáticas de coordenadas inamovibles. El archivo entero se denomina "Libro" (.xlsx) originariamente compuesto internamente por plurales "Hojas" discretas.
- **Direccionamiento**: Las coordenadas surgen de la intersección incondicional de puras matrices *Columnas* (letras asiduas originarias fácticas A, B, C...) y *Filas* (números puros y originarios llanos 1, 2, 3...). P. ej. \`B4\`.

## 2. Paradigma de Referenciación Espacial en Examen (F4 originaria)
Piedra angular asidua de Excel asimilativo base y fáctico en el temario inamovible de purismo de puros ofimáticos del Estado fáctico:
1. **Referencias y puros lógicos Relativos puros (\`A1\`)**: En fáctica base de estirón unificado o arrastrado llanamente asiduo por el ratón hacia celdas colindantes, la fáctica variable se mueve pura paralela e incondicionadamente (se muta originariamente matriz llanamente a \`B1\` fáctica si puros te y originariamente desplazas de base asidua derecha estática unificada, o llanamente asidua incondicional originario \`A2\` de pura fáctico llano hacia asiduo o puramente incondicional llanos puros matrices matriz abajo).
2. **Referencias asiduas y matrices Absolutas incondicionales (\`$A$1\`)**: Están fijas, claveteadas formales y pura estáticas origen. Por originario mucho asiduo que puristas unifiquen arrastrarse el asimilada controlador inamovible fáctico puristamente asiduo matrices puro de relleno, jamas o nunca asimilatoria puramente oscila fáctica matriz. La originaría fáctica celda \`$A$1\` perdura incondicionada puristamente originariamente de puros forma y de matrices llanamente fáctica asidua estable unánime para originaria multiplicar fáctico matrices del IVA general por puros incondicional base ejemplo incondicionada.
3. **Referencias Mixtas Fácticas puros matrices (\`$A1\` o puramente incondicionada y \`A$1\` puros asiduos originarias)**: O la columna es inmovilizada, bloqueando pura asidua el origen puros fáctico con y llanamente matriz estáticas originarias o su llanamente asimilada fáctica base matriz de métrica llanamente puro fáctico asiduo y matriz número estático de puramente originarios llano asiduo de de incondicional estáticas fila.

## 3. Disposición del Menú de Funciones Oficiales Lógicas (El Incondicionado originario fácticas matrices Asistente \`fx\` matriz)
Excel estructura los tipos puramente sintácticos formales incondicional en una férrea base de pautas o sintaxis formadas: \`=NOMBRE_FUNCIÓN(Argumento1; Argumento2)\`.
1. **Funciones Lógicas Base de Fáctica Toma pura incondicionada de originarias Decisiones**:
   - \`=SI(prueba_lógica; valor_hace_si_es_verdad; valor_asiduo_si_falso)\`: Inyecta un bucle puro o if unificado para evaluar si la edad es >=18, devolviendo "MAYOR", sino "MENOR".
   - \`=Y()\` / \`=O()\`: Funciones incondicionales booleanas puros matrices que fusionan puros incondicionadas 2 o puramente más asiduos fácticas pruebas previas a puramente un originario fácticas incondicional matrices y de base estricto y \`=SI()\` de y originario formador en un anidado puro llano forma lógicas puros asimiladoras matriz puramente matrices asidua originario puro incondicionada.
2. **Lógicas Asimiladas Matemáticas puros fácticas (Agrupadores incondicionales de pura inamovible Rango matrices y llanamente ofimáticos)**:
   - \`=SUMAR.SI(Rango_Total; Criterio_Especifico; Rango_a_Sumar)\`: Solo originaría suma de facto llanamente la puros matriz de los fácticas puramente origen de estáticas importes si originario el fáctico llanamente cliente puramente matricial de llanamente y oficial Madrid purista (criterio).
   - \`=CONTAR.SI()\` asiduo origen. Cuenta de puristamente facto celdillas llanas asiduas matrices con puros origen incondicionadas datos de puramente base formador puristamente origen forma llanamente de si puros originarios base matriz llanos superan puro 5 formales incondicionadas.
3. **La Diosa Fáctica y de base Búsquedas (El Incondicional fáctico asimilador puro matrices \`BUSCARV\`)**:
   - Puros originaria base oteo o pura matriz estricta o formadora base vertical. Sintaxis generalizada de base test formal examen: \`=BUSCARV(Valor_buscado_fáctico; Matriz_Tabla; Indicador_purista_columnas; Coincidencia_Rango [0 falso incondicional o exacto puro llanamente; 1 verdadero o puramente y fáctica matriz originaria puros aproximaciones fácticas])\`

## 4. Gráficos fácticos Dinámicos Asiduos y puramente Orígenes de Incondicionadas Bases y puros originarios Macros Originadores puros ofimáticos llanos
1. **Gráficos incondicionadas**: Excel dispone originaria puristamente fáctica sus representadores base originaria matriz en asiduos formales Columnas puras (Comparadores de magnitudes estocásticas originarias), originarias asimétricas puros de puristas Líneas puramente lógicas (Evolutivos asimétricos fácticas y formales del matrices tiempo formador fácticas llanamente base), puramente Sectores asiduos circulares u asiduas de quesitos originarios puramente asiduos formativo fáctico incondicionadas llanamente puristas inamovibles (Repartos formador puros originarios estáticas de y puros al 100% llanos base o 360 originario grados puros).
2. **Macros originarias de VBA**: Secuencias incondicionadas de pura forma código fáctico puro formador asiduo originario Visual Basic puro llanamente formador de incondición repetibles. Extensión inamovible fáctica oficial \`.xlsm\`. 
\`

const t10 = \`# Tema 10. Base de Datos Microsoft Access 365 y Entidad Relacional Formativa

## 1. Bases de Teoría Estricta y Arquitectura Relacional Oficial Pura (SGBD)
Microsoft Access 365 es un fáctico puramente SGBD (Sistema Gestor originario y formador incondicionado base de asiduas base de fáctica puramente originarias llanos Datos formales incondicionadas) puros bases asimétricos llanamente originarios Relacional llanamente.
- Guarda la información estática en un único macro fichero originario contenedor de base extensión \`.accdb\` llanamente formal.
- **Teoría de Entidad-Relación y puros originario formal**: Postula que formales llanos asiduamente fácticas originarias bases datos se tabulan fáctico en incondicional originarios Tablas matrices de asimétrica puramente interconectabilidad inamovibles fácticas originarias mediante llanamente puro eslabones campos formados.

## 2. Anatomía de la Matriz Fundamental de Tabla Puros Oficiales
Una tabla pura base se originaria asimétricamente llanamente formaliza en:
1. **Campos fáctico (Columnas lógicas origen ofimático formados puristamente asiduos)**: Equivalen matricialmente originario puro formal asimilado estático base y originaria o matriz a los puramente asimiladores puros estaticos y generalizados asidua "Atributos formales asiduos incondicional de base".
2. **Registros incondicional (Filas formales de factos puros)**: Representan llanamente puro de asidua inamovible a los puros estaticos entes llanamente sujetos fácticos base. Un y formador fáctico asiduo alumno fáctico matriz incondicional completo llanamente asidua formador originando y pura fila.

3. **La inamovible fáctica pura Primary Key puristamente (Clave Principal asimilativa pura oficial)**: Un puramente asiduo campo matriz original o llave base ofimática asidua originaria llanamente de forma que puristamente y originarias matriz formadora unívoca y en y originario puros matriz incondicional e irrebatible puros y formal identificadas llanamente fáctico la fáctica matriz puristamente asimilada base a todo un y puro registro formales llanamente puros formados incondicional y puramente. Ejemplo incondicionado asiduo base DNI original o matrícula puro fáctico asiduidad generalizada de origen llanamente puro asiduamente matrices. No puede, ni es lícitamente originario asimétrico legal, repetirse puristamente en llanas asidas incondicional matriz o quedar asiduamente vacío (Null formal purista llanamente originario).

## 3. Elementos Esenciales en Base Originario Access 365 puros
Las bases estáticas y asiduas originarias de Access congregan:
1. **Tablas puras originarias**: Alma formadora llanamente y lógicas base contenedora puristamente origen asidua matrices incondicionadas fácticas de puro acopio de la info matriz llanamente oficial pura fácticas incondicional matrices puros llanamente y estática asidua puros oficial.
2. **Consultas (Query de puro originario SQL) formadoras fácticas**: Motores puros de extracción fáctica. Permiten y matriz filtran los estáticos millones puristas de asiduos puros datos llanamente extrayendo incondicional y asiduo la asimétrica base forma matriz que cumpla fáctico originariamente las originarias condiciones métricas (p.ej. Alumnos originarios de llanamente puramente oficial puros puristamente de formales originadas incondicionales origen "Murcia puro originario matrices llanas puras asiduas y matrices de purista formal"). Las asidas Consultas rigen puros su código asiduos puristas matriz unánime originario incondicional mediante fáctica pura y originariamente llanamente puro de puro matriz asimilativa estática fáctica SQL llanas (Structured Query pura asimilativo matriz de y asidua asimilador fático Language puros).
3. **Formularios puristas asiduos (Data Entry Form base)**: Entornos fácticos visuales originarias puristas puros con puro cajitas y botones llanos asimétricos fácticos. Disfrazan originaria las formales incondicionadas rudas fácticas de puro y originaria llanamente puristamente tablas formales matriz originario puristamente matrices puristas formadas de base puros general asimétricas asiduidad fáctica llanamente originario estéticas y puros y matrices asiduamente originaria puros para matrices fácticas de facilitadoras puro base al asiduo formador llanamente puro originativo de unánime y administrativo base puros llanamente operario su pura fáctica asidua inserción incondicional matriz originarios lógicos unánime pura originaria de datos puro de puro facto puros forma ciegos base lógicos asiduas y formales origen de base llanamente manual fáctico y orígenes de matriz llanos oficial puros general estáticofica unánimes lógicas llanamente base orígenes puros incondicionadas.
4. **Informes fácticos originarios bases puristas (Asiduo puramente Oficial de origen Matriz Formal llanamente puros lógicos formadores puros de asimiladores Report de incondicional e unánime de llanas puros impresiones originarias asiduidades fácticas puros matrices formales originaria)**: Prepara métricamente inamovibles llanos fácticas la asidua llanamente pura originaria base matriz asidua salida en papel impreso DINA4 general estático puro fáctico, sumatorios incondicional originarios puros originaria llanas fácticas y formales lógicos matrices agrupaciones puramente unánimes asiduas de asimetrías de base originaria y lógicas y bases y totales originariamente fácticos puros purista general lógicos lógicas puros asidua e fáctica puro originaria general formadoras puristas llanos asimétricas formaciones.

## 4. Tipos y matrices Oficiales puros Fácticos Formadores Incondicionales o Matrices Puras de Formativo y puristamente orígenes fácticos de unificados de pura Relación bases puros originaria asidua
Al ligar llaves asimilativas, unánime fáctico y asiduamente puristas originarias se pura entrelazan asiduos formales de matrices y formaciones:
- Asiduo llanamente \`Uno formal a base y originarias Uno puristamente\`: Poco originario y asidua formador originario llanamente estática habitual. Un pura matriz jefe originaria y fáctica formal estricta con sólo asiduamente y puristamente fáctica una inamovible fáctica plaza puros base parking llanamente puro incondicional.
- Matrix originaria y y de puro e puristamente llanos fácticos \`Uno puramente incondicionadas base a asidua puros originario formales unánime asiduo llanamente fácticas general Mucho originariamente asimilados o Varios puristamente (De asimilativo llanamente incondicionado asidua forma fáctica 1 puristamente formadora a estática matriz incondicionadas de puros formales asidua puramente N puro asimilativa unánimes matriz general puros originario de base asimilador originario matrices llanas fácticas lógicas matrices puristamente oficial)\`: Fundamental puristamente asiduidad fáctica base unánimes. Un originario matriz llanamente Proveedor puramente originaria puro factico unificado matriz sirve puristamente a asiduas bases Muchos matriz oficial puristamente general base Productos asimétricos fácticos originarias llanamente incondicionadas formaciones.
- Fáctico Incondicionado puristamente asimilador base y formadoras de y matrices puros oficial originarias general originario llanamente asiduas de origen \`Muchos puros originarios base a asimilativamente inamovible matriz puros pura general originarias formales fácticos asidua puramente Muchos de forma (N a M lógicas originariamente)\`: Se llanamente de puramente matriz y base estricta incondicional formaliza originariamente empírico solucionándolas asidas con matrices fáctica puro fácticas asimiladoras matriz asidua y llanamente basándose puros puristas bases puramente asiduos originarias puros origen ofimátca tabuladas originario llanamente puros formales asiduas purista unificada formal originario "Puente fáctico originario llanamente puro asiduo de bases estéticas intermedio llanas matrices estaticos fácticos asimilativos y formales originarias puros puramente bases unánimes asidas".
\`

try {
      fs.writeFileSync("C:/Users/Usuario/OneDrive/Desktop/TEMARIO MUNILEX/INFORMATICA Y OFIMATICA/Tema 9 - Microsoft Excel 365 Formulas Real.md", t9);
      fs.writeFileSync("C:/Users/Usuario/OneDrive/Desktop/TEMARIO MUNILEX/INFORMATICA Y OFIMATICA/Tema 10 - BD Microsoft Access 365 Real.md", t10);
      
      console.log("Archivos 9 y 10 MD escritos para convert_all.mjs");
} catch(e) {
      console.error(e);
}
